"""Distribution/runtime helpers for source, packaged, and AppImage runs."""

from __future__ import annotations

from dataclasses import dataclass
import os
import shlex
import shutil
import stat
import subprocess
import sys

APP_NAME = "WaveLinux"
APP_DESKTOP_ID = "io.github.excalprimeacct_gif.WaveLinux"
APPIMAGE_FILENAME = "WaveLinux.AppImage"
WRAPPER_FILENAME = "wavelinux"
DESKTOP_FILENAME = f"{APP_DESKTOP_ID}.desktop"
ICON_FILENAME = "wavelinux.png"


@dataclass(frozen=True)
class AppImageInstallResult:
    appimage_path: str
    desktop_path: str
    icon_path: str
    wrapper_path: str


def app_root() -> str:
    """Return the directory that contains bundled resources."""
    if getattr(sys, "frozen", False):
        bundle_dir = getattr(sys, "_MEIPASS", None)
        if bundle_dir:
            return os.path.abspath(bundle_dir)
        return os.path.dirname(os.path.abspath(sys.executable))
    return os.path.dirname(os.path.abspath(__file__))


def resource_path(*parts: str) -> str:
    return os.path.join(app_root(), *parts)


def current_appimage_path(*, environ=None, argv=None) -> str | None:
    env = environ if environ is not None else os.environ
    path = env.get("APPIMAGE")
    if path:
        return os.path.abspath(path)
    args = argv if argv is not None else sys.argv
    if args:
        candidate = os.path.abspath(args[0])
        if candidate.endswith(".AppImage") and os.path.exists(candidate):
            return candidate
    return None


def is_running_in_appimage(*, environ=None, argv=None) -> bool:
    return current_appimage_path(environ=environ, argv=argv) is not None


def installed_appimage_path(*, home=None) -> str:
    home_dir = os.path.expanduser("~") if home is None else os.path.abspath(home)
    return os.path.join(home_dir, ".local", "bin", APPIMAGE_FILENAME)


def installed_wrapper_path(*, home=None) -> str:
    home_dir = os.path.expanduser("~") if home is None else os.path.abspath(home)
    return os.path.join(home_dir, ".local", "bin", WRAPPER_FILENAME)


def installed_desktop_path(*, home=None) -> str:
    home_dir = os.path.expanduser("~") if home is None else os.path.abspath(home)
    return os.path.join(home_dir, ".local", "share", "applications", DESKTOP_FILENAME)


def installed_icon_path(*, home=None) -> str:
    home_dir = os.path.expanduser("~") if home is None else os.path.abspath(home)
    return os.path.join(
        home_dir,
        ".local",
        "share",
        "icons",
        "hicolor",
        "512x512",
        "apps",
        ICON_FILENAME,
    )


def launch_command(*, home=None) -> list[str]:
    """Return the launch command for the current runtime mode."""
    appimage = current_appimage_path()
    if appimage:
        return [appimage]
    if getattr(sys, "frozen", False):
        return [os.path.abspath(sys.executable)]
    return [sys.executable, resource_path("main.py")]


def launch_command_string(*, home=None) -> str:
    return " ".join(shlex.quote(part) for part in launch_command(home=home))


def desktop_exec_command(*, home=None) -> str:
    """Return a Desktop Entry-safe Exec= command."""
    def _quote(part: str) -> str:
        if part and all(ch not in part for ch in ' \t"\'\\'):
            return part
        escaped = part.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    return " ".join(_quote(part) for part in launch_command(home=home))


def install_current_appimage(*, home=None) -> AppImageInstallResult:
    source = current_appimage_path()
    if not source:
        raise RuntimeError("WaveLinux is not running from an AppImage.")
    if not os.path.isfile(source):
        raise RuntimeError(f"AppImage not found at {source}.")

    home_dir = os.path.expanduser("~") if home is None else os.path.abspath(home)
    target_appimage = installed_appimage_path(home=home_dir)
    target_wrapper = installed_wrapper_path(home=home_dir)
    target_desktop = installed_desktop_path(home=home_dir)
    target_icon = installed_icon_path(home=home_dir)

    os.makedirs(os.path.dirname(target_appimage), exist_ok=True)
    os.makedirs(os.path.dirname(target_desktop), exist_ok=True)
    os.makedirs(os.path.dirname(target_icon), exist_ok=True)

    if os.path.abspath(source) != os.path.abspath(target_appimage):
        shutil.copy2(source, target_appimage)
    os.chmod(
        target_appimage,
        stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
        | stat.S_IRGRP | stat.S_IXGRP
        | stat.S_IROTH | stat.S_IXOTH,
    )

    icon_source = resource_path("icon.png")
    if os.path.exists(icon_source):
        shutil.copy2(icon_source, target_icon)

    wrapper_contents = (
        "#!/bin/sh\n"
        "# Auto-generated by WaveLinux AppImage install.\n"
        f'exec "{target_appimage}" "$@"\n'
    )
    with open(target_wrapper, "w", encoding="utf-8") as handle:
        handle.write(wrapper_contents)
    os.chmod(
        target_wrapper,
        stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
        | stat.S_IRGRP | stat.S_IXGRP
        | stat.S_IROTH | stat.S_IXOTH,
    )

    desktop_contents = (
        "[Desktop Entry]\n"
        "Name=WaveLinux\n"
        "Comment=PipeWire Audio Router & Mixer\n"
        f"Exec={target_wrapper}\n"
        "Icon=wavelinux\n"
        "Type=Application\n"
        "Categories=AudioVideo;Audio;Mixer;\n"
        "Keywords=audio;mixer;pipewire;routing;\n"
        "StartupNotify=true\n"
    )
    with open(target_desktop, "w", encoding="utf-8") as handle:
        handle.write(desktop_contents)

    try:
        subprocess.run(
            ["update-desktop-database", os.path.dirname(target_desktop)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
            check=False,
        )
    except Exception:
        pass

    return AppImageInstallResult(
        appimage_path=target_appimage,
        desktop_path=target_desktop,
        icon_path=target_icon,
        wrapper_path=target_wrapper,
    )
