#!/usr/bin/env bash
# WaveLinux local source installer.
# This installs desktop integration for a checkout of the repository.
# End users should prefer the AppImage release.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DESKTOP_FILE="$HOME/.local/share/applications/io.github.duskyprojects.WaveLinux.desktop"
ICON_DIR="$HOME/.local/share/icons/hicolor/512x512/apps"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/wavelinux"
INSTALL_ARCH_DEPS=0

for arg in "$@"; do
    case "$arg" in
        --arch-deps)
            INSTALL_ARCH_DEPS=1
            ;;
        *)
            echo "Unknown argument: $arg" >&2
            echo "Usage: ./install.sh [--arch-deps]" >&2
            exit 1
            ;;
    esac
done

echo "╔══════════════════════════════════════════╗"
echo "║     WaveLinux Local Source Installer     ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "This installs a launcher for the current source checkout."
echo "For portable multi-distro installs, use the GitHub AppImage release."
echo ""

if [ "${INSTALL_ARCH_DEPS}" -eq 1 ]; then
    if ! command -v pacman >/dev/null 2>&1; then
        echo "--arch-deps was requested, but pacman is not available on this system." >&2
        exit 1
    fi
    echo "→ Installing Arch runtime dependencies..."
    sudo pacman -S --needed --noconfirm \
        python \
        python-pyqt6 \
        pipewire \
        pipewire-pulse \
        wireplumber \
        libpulse \
        rnnoise \
        swh-plugins \
        procps-ng
    echo "→ Installing optional RNNoise LADSPA plugin when an AUR helper is available..."
    if ! pacman -Qi noise-suppression-for-voice >/dev/null 2>&1; then
        if command -v paru >/dev/null 2>&1; then
            paru -S --needed --noconfirm noise-suppression-for-voice
        elif command -v yay >/dev/null 2>&1; then
            yay -S --needed --noconfirm noise-suppression-for-voice
        else
            echo "  No AUR helper found; skipping noise-suppression-for-voice."
        fi
    fi
fi

echo "→ Installing desktop launcher, wrapper and icon..."
mkdir -p "$HOME/.local/share/applications" "$ICON_DIR" "$BIN_DIR"

if [ -f "$SCRIPT_DIR/icon.png" ]; then
    cp "$SCRIPT_DIR/icon.png" "$ICON_DIR/wavelinux.png"
fi

cat > "$WRAPPER" <<EOF
#!/bin/sh
# Auto-generated by WaveLinux install.sh.
SOURCE_DIR="${SCRIPT_DIR}"
if [ ! -f "\$SOURCE_DIR/main.py" ]; then
    echo "WaveLinux source tree not found at \$SOURCE_DIR." >&2
    echo "Re-run install.sh from the new checkout location." >&2
    exit 1
fi
exec python3 "\$SOURCE_DIR/main.py" "\$@"
EOF
chmod 755 "$WRAPPER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=WaveLinux
Comment=PipeWire Audio Router & Mixer
Exec=${WRAPPER}
Icon=wavelinux
Type=Application
Categories=AudioVideo;Audio;Mixer;
Keywords=audio;mixer;pipewire;routing;
StartupNotify=true
EOF

update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true

echo ""
echo "✅  WaveLinux source launcher installed."
echo ""
echo "Run it from your application menu or with:"
echo "  ${WRAPPER}"
echo ""
echo "Required host tools:"
echo "  pactl  pw-dump  wpctl  parec  pipewire  pw-cli"
echo ""
echo "If you move this checkout, re-run ./install.sh from the new path."
