#!/bin/bash
# WaveLinux Installer for CachyOS / Arch-based distros (KDE)
set -e

echo "╔══════════════════════════════════════════╗"
echo "║        WaveLinux Installer               ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Install dependencies via pacman.
# Why each one is here:
#   python / python-pyqt6 — runtime + GUI
#   pipewire / pipewire-pulse / wireplumber — the audio server we drive
#   libpulse — provides `pactl` and `parec` (peak meters use parec)
#   rnnoise — base library for the noise-suppressor LADSPA plugin
#   swh-plugins — provides sc4m_1916 (compressor, mono) and gate_1410
#                 (gate). The limiter is implemented with PipeWire
#                 builtins (linear + clamp) so it doesn't depend on
#                 this package.
echo "→ Installing dependencies..."
sudo pacman -S --needed --noconfirm \
    python \
    python-pyqt6 \
    pipewire \
    pipewire-pulse \
    wireplumber \
    libpulse \
    rnnoise \
    swh-plugins

# Install the RNNoise LADSPA plugin from the AUR. Required for the
# Noise-Suppression effect; without it, the FX dialog grey-outs that row.
# Skipped if WaveLinux's installer is being run inside an environment
# without an AUR helper (CI, docker, fresh chroot).
echo "→ Installing RNNoise plugin (noise-suppression-for-voice)..."
if ! pacman -Qi noise-suppression-for-voice > /dev/null 2>&1; then
    if command -v paru >/dev/null 2>&1; then
        paru -S --needed --noconfirm noise-suppression-for-voice
    elif command -v yay >/dev/null 2>&1; then
        yay -S --needed --noconfirm noise-suppression-for-voice
    else
        echo "⚠ Could not find 'paru' or 'yay'. Please install 'noise-suppression-for-voice' manually from the AUR."
    fi
else
    echo "  Already installed."
fi

# Install .desktop file, launcher wrapper, and icon.
#
# We deliberately install a tiny wrapper at ~/.local/bin/wavelinux that
# resolves the source-tree path at install time and the .desktop's
# Exec= invokes that wrapper. This means:
#   - the user can move the source tree as long as they re-run install.sh
#   - if the user `rm -rf`s the source tree, the wrapper fails with a
#     clear error message (instead of the .desktop entry silently no-op
#     or worse, the KDE menu launching nothing)
#   - there is exactly ONE place to update the source path, not two
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DESKTOP_FILE="$HOME/.local/share/applications/wavelinux.desktop"
ICON_DIR="$HOME/.local/share/icons/hicolor/512x512/apps"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/wavelinux"

echo "→ Installing desktop launcher, wrapper and icon..."
mkdir -p "$HOME/.local/share/applications"
mkdir -p "$ICON_DIR"
mkdir -p "$BIN_DIR"

if [ -f "$SCRIPT_DIR/icon.png" ]; then
    cp "$SCRIPT_DIR/icon.png" "$ICON_DIR/wavelinux.png"
fi

cat > "$WRAPPER" <<EOF
#!/bin/sh
# Auto-generated by WaveLinux install.sh — do not edit by hand.
# Re-run ${SCRIPT_DIR}/install.sh after moving the source tree.
SOURCE_DIR="${SCRIPT_DIR}"
if [ ! -f "\$SOURCE_DIR/main.py" ]; then
    echo "WaveLinux source tree not found at \$SOURCE_DIR." >&2
    echo "Either restore it, move it back, or re-run install.sh from" >&2
    echo "the new location to point this launcher at the new path." >&2
    exit 1
fi
exec python3 "\$SOURCE_DIR/main.py" "\$@"
EOF
chmod 755 "$WRAPPER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=WaveLinux
Comment=PipeWire Audio Router & Mixer
Exec=${WRAPPER}
Icon=wavelinux
Type=Application
Categories=AudioVideo;Audio;Mixer;
Keywords=audio;mixer;pipewire;routing;
StartupNotify=true
EOF

# Refresh the desktop-file database so the KDE menu picks up the launcher.
update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true

echo ""
echo "✅  WaveLinux installed!"
echo ""
echo "You can now:"
echo "  1. Find 'WaveLinux' in your KDE application menu"
echo "  2. Or run it directly:  wavelinux  (if ~/.local/bin is on \$PATH)"
echo "                          python3 ${SCRIPT_DIR}/main.py"
echo ""
echo "If you move or remove ${SCRIPT_DIR},"
echo "re-run install.sh from the new location (the launcher wrapper at"
echo "${WRAPPER} stores the path so it knows where main.py lives)."
echo ""
echo "To uninstall and wipe state (useful if app names look stuck on"
echo "old values like 'audio-src'):"
echo "  ${SCRIPT_DIR}/uninstall.sh"
echo ""
