#!/bin/sh
set -eu

HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

if [ -d "${HERE}/usr/lib/ladspa" ]; then
    export WAVELINUX_BUNDLED_LADSPA_PATH="${HERE}/usr/lib/ladspa"
fi

exec "${HERE}/usr/lib/wavelinux/WaveLinux" "$@"
