#!/usr/bin/env bash
set -euo pipefail

APP_DISPLAY_NAME="${WAVELINUX_APP_DISPLAY_NAME:-WaveLinux5}"
GRAPH_PREFIX="${WAVELINUX_GRAPH_PREFIX:-wavelinux5}"
CONFIG_DIR="${WAVELINUX_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/$GRAPH_PREFIX}"
CONFIG_FILE="$CONFIG_DIR/config.json"
ASOUNDRC="${WAVELINUX_ASOUNDRC:-$HOME/.asoundrc}"
START_MARKER="# >>> $APP_DISPLAY_NAME ALSA aliases >>>"
END_MARKER="# <<< $APP_DISPLAY_NAME ALSA aliases <<<"

safe_alias() {
  local value="$1"
  value="${value,,}"
  value="${value//[^a-z0-9_]/_}"
  value="${value##_}"
  value="${value%%_}"
  if [[ -z "$value" ]]; then
    value="device"
  fi
  printf '%s' "$value"
}

alsa_quote() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

emit_pcm() {
  local alias="$1"
  local device="$2"
  local description="$3"
  alias="$(safe_alias "$alias")"
  device="$(alsa_quote "$device")"
  description="$(alsa_quote "$description")"

  cat <<ALSA
pcm.$alias {
    type pulse
    device "$device"
    hint {
        show on
        description "$description"
    }
}

ctl.$alias {
    type pulse
}

ALSA
}

emit_aliases() {
  echo "$START_MARKER"
  echo "# Generated by $APP_DISPLAY_NAME. Re-run scripts/install-local.sh to refresh."
  echo
  emit_pcm "${GRAPH_PREFIX}_mic" "${GRAPH_PREFIX}-mic" "$APP_DISPLAY_NAME Processed Mic"

  if command -v jq >/dev/null 2>&1 && [[ -f "$CONFIG_FILE" ]]; then
    jq -r '.mixes[]? | [.id, .name, .virtual_source_name] | @tsv' "$CONFIG_FILE" |
      while IFS=$'\t' read -r id name source; do
        [[ -n "${id:-}" && -n "${source:-}" ]] || continue
        emit_pcm "${GRAPH_PREFIX}_mix_$id" "$source" "$APP_DISPLAY_NAME ${name:-$id} Mix"
      done

    jq -r '.channels[]? | [.id, .name, .virtual_sink_name] | @tsv' "$CONFIG_FILE" |
      while IFS=$'\t' read -r id name sink; do
        [[ -n "${id:-}" && -n "${sink:-}" ]] || continue
        emit_pcm "${GRAPH_PREFIX}_channel_$id" "$sink.monitor" "$APP_DISPLAY_NAME ${name:-$id} Channel"
      done
  else
    emit_pcm "${GRAPH_PREFIX}_mix_monitor" "${GRAPH_PREFIX}_mix_monitor_source" "$APP_DISPLAY_NAME Monitor Mix"
    emit_pcm "${GRAPH_PREFIX}_mix_stream" "${GRAPH_PREFIX}_mix_stream_source" "$APP_DISPLAY_NAME Stream Mix"
    emit_pcm "${GRAPH_PREFIX}_channel_hardware_in" "${GRAPH_PREFIX}_channel_hardware_in.monitor" "$APP_DISPLAY_NAME Input Channel"
    emit_pcm "${GRAPH_PREFIX}_channel_music" "${GRAPH_PREFIX}_channel_music.monitor" "$APP_DISPLAY_NAME Music Channel"
  fi

  echo "$END_MARKER"
}

tmp_existing="$(mktemp)"
tmp_block="$(mktemp)"
tmp_output="$(mktemp)"
trap 'rm -f "$tmp_existing" "$tmp_block" "$tmp_output"' EXIT

if [[ -f "$ASOUNDRC" ]]; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skip = 1; next }
    $0 == end { skip = 0; next }
    !skip { print }
  ' "$ASOUNDRC" > "$tmp_existing"
fi

emit_aliases > "$tmp_block"

{
  if [[ -s "$tmp_existing" ]]; then
    cat "$tmp_existing"
    echo
  fi
  cat "$tmp_block"
} > "$tmp_output"

install -m 0644 "$tmp_output" "$ASOUNDRC"
echo "Installed $APP_DISPLAY_NAME ALSA aliases to $ASOUNDRC"
