#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wavelinux"
CONFIG_FILE="$CONFIG_DIR/config.json"
ASOUNDRC="${WAVELINUX_ASOUNDRC:-$HOME/.asoundrc}"
START_MARKER="# >>> WaveLinux ALSA aliases >>>"
END_MARKER="# <<< WaveLinux ALSA aliases <<<"

safe_alias() {
  local value="$1"
  value="${value,,}"
  value="${value//[^a-z0-9_]/_}"
  value="${value##_}"
  value="${value%%_}"
  if [[ -z "$value" ]]; then
    value="device"
  fi
  printf '%s' "$value"
}

alsa_quote() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

emit_pcm() {
  local alias="$1"
  local device="$2"
  local description="$3"
  alias="$(safe_alias "$alias")"
  device="$(alsa_quote "$device")"
  description="$(alsa_quote "$description")"

  cat <<ALSA
pcm.$alias {
    type pulse
    device "$device"
    hint {
        show on
        description "$description"
    }
}

ctl.$alias {
    type pulse
}

ALSA
}

emit_aliases() {
  echo "$START_MARKER"
  echo "# Generated by WaveLinux. Re-run scripts/install-local.sh to refresh."
  echo

  if command -v jq >/dev/null 2>&1 && [[ -f "$CONFIG_FILE" ]]; then
    jq -r '.mixes[]? | [.id, .name, .virtual_source_name] | @tsv' "$CONFIG_FILE" |
      while IFS=$'\t' read -r id name source; do
        [[ -n "${id:-}" && -n "${source:-}" ]] || continue
        emit_pcm "wavelinux_mix_$id" "$source" "WaveLinux ${name:-$id} Mix"
      done

    jq -r '.channels[]? | [.id, .name, .virtual_sink_name] | @tsv' "$CONFIG_FILE" |
      while IFS=$'\t' read -r id name sink; do
        [[ -n "${id:-}" && -n "${sink:-}" ]] || continue
        emit_pcm "wavelinux_channel_$id" "$sink.monitor" "WaveLinux ${name:-$id} Channel"
      done
  else
    emit_pcm "wavelinux_mix_monitor" "wavelinux_mix_monitor_source" "WaveLinux Monitor Mix"
    emit_pcm "wavelinux_mix_stream" "wavelinux_mix_stream_source" "WaveLinux Stream Mix"
    emit_pcm "wavelinux_channel_hardware_in" "wavelinux_channel_hardware_in.monitor" "WaveLinux Hardware In Channel"
    emit_pcm "wavelinux_channel_music" "wavelinux_channel_music.monitor" "WaveLinux Music Channel"
  fi

  echo "$END_MARKER"
}

tmp_existing="$(mktemp)"
tmp_block="$(mktemp)"
tmp_output="$(mktemp)"
trap 'rm -f "$tmp_existing" "$tmp_block" "$tmp_output"' EXIT

if [[ -f "$ASOUNDRC" ]]; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skip = 1; next }
    $0 == end { skip = 0; next }
    !skip { print }
  ' "$ASOUNDRC" > "$tmp_existing"
fi

emit_aliases > "$tmp_block"

{
  if [[ -s "$tmp_existing" ]]; then
    cat "$tmp_existing"
    echo
  fi
  cat "$tmp_block"
} > "$tmp_output"

install -m 0644 "$tmp_output" "$ASOUNDRC"
echo "Installed WaveLinux ALSA aliases to $ASOUNDRC"
